### ISSUE TITLE
URL Link formatting inconsistent.

### ISSUE THREAD

**Issue by Dulanic** [matthewpi/vscode-caddyfile-support#10]
**System Information**
* Operating System:  N/A
* Extension Version: 0.1.1
* VSCode Version: 1.55.1
* `caddy` Version: 2.3

**Describe the bug**
Formatting of the code is consistent for some blocks. See the http of the 1st block is one color, but the 2nd is another.

**Steps to Reproduce**
I have yet to determine the root cause, but it seems to be confusion around the {}
Paste this into vs code and format as Caddyfile.
```
https://domain.com {
  import main
  root * /www/websites/domain.com
  file_server
  redir /img /img/
  handle_path /img/* {
    root * /www/img
    file_server
  }  
  redir /files /files/
  handle_path /files/* {
    root * /www/files
    file_server browse
  }  
}
https://subdomain1.domain.com {
  import main
  file_server
  root * /www/websites/subdomain1.domain.com
  handle_path /img/* {
    root * /www/websites/subdomain1.domain.com/images
    file_server
  }    
}
https://subdomain2.domain.com {
  import main
  reverse_proxy subdomain2:9000 {
    import proxyheaders
  }
}
https://subdomain3.domain.com {
  import main
  reverse_proxy http://192.168.2.155:10000 {
    import proxyheaders
  }
}
```

**Expected Behavior**
Consistent formatting

**Screenshots**
![image](https://user-images.githubusercontent.com/2948206/114712790-1d284b80-9cf6-11eb-8edd-9dac2a328358.png)

**Comment by matthewpi** [comment]
I am unable to reproduce this with the Caddyfile you submitted.

OS: `Windows 10 Pro 10.0.19041`
VSCode Version: `v1.56.0`
Extension version: `v0.1.1`

![yu50zvt24paHvfyO](https://user-images.githubusercontent.com/26559841/117683311-2e3b6f80-b171-11eb-99f7-3dc39de51561.png)
![VtKb8M5WSMTsudYC](https://user-images.githubusercontent.com/26559841/117683363-3a273180-b171-11eb-8c0b-23b09071c8a7.png)

You can inspect how a symbol is being highlighted by calling `Developer: Inspect Editor Tokens and Scopes` in the [Command Palette](https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette)

**Comment by Dulanic** [comment]
Closing, I can no longer replicate. Might have been caused by the version of caddy at the time, unsure.

**Comment by Dulanic** [comment]
> > Closing, I can no longer replicate. Might have been caused by the version of caddy at the time, unsure.
> 
> The caddy executable is only for code formatting, it has nothing to do with highlighting, suggestions, or hover documentation.

Understood, I know it happened as can be seen in my screenshot, but no clue why it isn't happening now. I haven't change my environment. If I can replicate  again I'll reopen.
