### ISSUE TITLE
Using spaces instead of tab

### ISSUE THREAD

**Issue by FireMasterK** [matthewpi/vscode-caddyfile-support#106]
**Is your request related to a problem?**
I would like to use 4 spaces instead of the actual tab character.

**Describe the solution you would like**
Use the tab settings specified in vscode.

**Describe any alternatives you have considered**
A workaround would be to click on the tab options and then click on "Convert indentation to spaces" and Save without formatting (Ctrl K + S)

**Comment by francislavoie** [comment]
`caddy fmt` uses tabs, for the same reason as `gofmt` uses tabs. Just use tabs.

**Comment by matthewpi** [comment]
I don't intend on changing this.
