### ISSUE TITLE
Open VSX

### ISSUE THREAD

**Issue by Dulanic** [matthewpi/vscode-caddyfile-support#12]
Would you mind adding your extension to open vsx? That way I can use this extension within code server. If not no biggie.

https://open-vsx.org/
https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

**Comment by matthewpi** [comment]
For sure.  I'll take a look into doing this later today.

**Comment by matthewpi** [comment]
The extension is available on Open-VSX as of 3 days ago.
