### ISSUE TITLE
header Content-Type text/* ruins highlighting

### ISSUE THREAD

**Issue by tomquas** [matthewpi/vscode-caddyfile-support#231]
**System Information**
* Operating System: macos
* Extension Version: 0.2.0
* VSCode Version: 1.69.0
* `caddy` Version: 2.5.2

**Describe the bug**
i defined the section below to import from host specs:

```
(encode) {
  encode {
    gzip
    zstd
    match {
      header Content-Type application/json*
      header Content-Type application/protobuf*
      header Content-Type application/javascript*
      header Content-Type text/*
    }
  }
}
```

the last header statement's text/* ruins highlighting such that all following statements are shown without coloring. By moving that line up and down you can track the effect to this part of the header statement.

**Expected Behavior**
Keep highlighting going.

**Comment by matthewpi** [comment]
I'm not sure I can reproduce this.  Here is how that content is highlighted for ![Screenshot from 2022-07-18 10-19-21](https://user-images.githubusercontent.com/26559841/179556744-6da8e0fb-7334-4240-8ca2-1eb05ddd85aa.png).
![Screenshot from 2022-07-18 10-18-11](https://user-images.githubusercontent.com/26559841/179556604-39935538-d13d-4654-b12a-950a9d96d3eb.png)

**Comment by tomquas** [comment]
hmm, can i ask what theme you're using? here's a shot of my view on this...
<img width="535" alt="Screen Shot 2022-07-19 at 08 53 35" src="https://user-images.githubusercontent.com/564311/179685490-e7cd8d73-2694-48e4-814f-ce8f70fbacd0.png">

**Comment by francislavoie** [comment]
Are you sure you're using the Caddyfile syntax highlighting? Check the bottom-right of your IDE, does it say "Caddyfile"?

Looks like the `/*` is being parsed as a comment, but `/*` is not a comment in the Caddyfile, so it must be from some other language.

**Comment by tomquas** [comment]
you're totally right. and i feel stupid...

the file was named 'Caddyfile-dev' and VS chose the Groovy highlighter.
copied to file to 'Caddyfile' and all works well.
sorry.

is there a way for the plugin to register 'Caddyfile*' for caddy-style highlighting?

**Comment by francislavoie** [comment]
FWIW I'd appreciate having `Caddyfile*` work too, but it should exclude `caddyfile.go` and `caddyfile.md` which tend to come up reasonably often in the Caddy codebase and docs.
