### ISSUE TITLE
Can the auto formatting be disabled?

### ISSUE THREAD

**Issue by eslym** [matthewpi/vscode-caddyfile-support#9]
That feature keeps replace spaces to tabs when save, which i dont like at all

**Comment by eslym** [comment]
set the caddy path to /bin/false solved my problem, so i guess i will just close this issue

**Comment by eslym** [comment]
set the caddy path to /bin/false solved my problem, so i guess i will just close this issue

**Comment by matthewpi** [comment]
You can disable the format on save functionality by setting
'''
[caddyfile]: {
    "editor.formatOnSave": false,
},
'''
In your VSCode settings.
